### ISSUE TITLE
Add example of caching pip dependencies

### ISSUE THREAD

**Issue by merwok** [circleci/cci-demo-flask#2]
Hello!  This example installs JS dependencies with yarn and caches the yarn directory, which is not super useful for a Python example.  It would be helpful to show a save_cache step using pip requirement files (we often split runtime and tests deps in two files) and the pip cache directory.

I have to say that the doc at https://circleci.com/docs/2.0/caching/ is confusing.  From the phrasing of the text, I’m not sure if the restore_cache step will skip the install step or just make it a fast no-op.  I don’t know if I should have one key or many, and if it should checksum my pip files (and be 100% invalidated when I just add one dependency) or just have a v1 prefix that I can decide to update only when I’ve made many changes to my dependencies and I want a new cache entry.

Thanks for considering this!

**Comment by merwok** [comment]
These resources offer more information:
* https://github.com/circleci/cci-demo-walkthrough/blob/master/.circleci/config.yml
* https://circleci.com/docs/2.0/project-walkthrough/#introduction

**Comment by keybits** [comment]
Thanks for reporting this. We're updating the demo applications for 2.0 in the next few days and we'll make sure to address this issue.

**Comment by keybits** [comment]
The new demo Flask app is here: https://github.com/CircleCI-Public/circleci-demo-python-flask

There's a Django app too: https://github.com/CircleCI-Public/circleci-demo-python-django

No more Yarn! We'll be updating and improving both of the above apps over the coming weeks.

**Comment by merwok** [comment]
Thanks!

**Comment by brianmhunt** [comment]
The notes strategies do not appear to be effective with `pipenv`.
